name: Task Manager DevSecOps
run-name: ${{ github.actor }} is running this pipeline
on: [push]

jobs:

  Backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running ${{ github.jobs.Backend.name }} job"

      - name: Checkout repository code
        uses: actions/checkout@v5

      - run: cd backend/

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: echo "Backend successfully setup"

  Frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running ${{ github.jobs.Frontend.name }} job"

      - name: Checkout repository code
        uses: actions/checkout@v5

      - run: cd frontend/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
